# Generated by Django 4.1 on 2022-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0004_image_delete_resimler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
