# Generated by Django 4.1 on 2022-12-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0006_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
