# Generated by Django 4.1 on 2022-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0008_resimler_delete_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resimler",
            options={"get_latest_by": "date_created"},
        ),
        migrations.AlterField(
            model_name="resimler",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
