# Generated by Django 4.1 on 2022-12-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0009_alter_resimler_options_alter_resimler_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resimler",
            options={"get_latest_by": "created_at"},
        ),
    ]
